replicaCount: 1

image:
  repository: tesla/vehicle-command
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 4443
  targetPort: 4443
  nodePort: 30443

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  - name: TESLA_VERBOSE
    value: "true"

tlsCert: |
  # Will be replaced with actual cert
tlsKey: |
  # Will be replaced with actual key
privateKey: |
  # Will be replaced with actual key
